"""
Claude -> Gemini Failover Canary Test Suite (tests/test_voice_canary_failover.py)

Validates Criterion 4:
- Claude rate-limit / quota failure (HTTP 429) triggers automatic Gemini fallback
- Conversation seamlessly continues without dropped calls
- Audio output is successfully generated by Gemini and transmitted to caller
- No duplicate tool executions or duplicate user-facing turns
- Audit logging records failover event with primary and fallback metadata
- Metrics counter `llm_failover_events_total` is incremented
- Cooldown window routes subsequent turns directly to fallback
"""

import asyncio
import sys
import unittest
from pathlib import Path
from typing import Iterator, Union

_VOICE_DIR = str(Path(__file__).resolve().parents[1] / "src" / "voice")
_AGENT_DIR = str(Path(__file__).resolve().parents[1] / "src" / "agent")
_INFERENCE_DIR = str(Path(__file__).resolve().parents[1] / "src" / "inference")
for p in (_VOICE_DIR, _AGENT_DIR, _INFERENCE_DIR):
    if p not in sys.path:
        sys.path.insert(0, p)

from audit import AuditLogger
from conversation_manager import ConversationManager
from handoff_detector import HandoffDetector
from llm_provider import (
    BaseLLMProvider,
    FallbackLLMProvider,
    LLMQuotaExceededError,
)
from metrics import MetricsRegistry
from stt_service import MockSTTService, STTEvent, STTEventType
from telephony_models import CallSession
from tts_service import MockTTSService
from voice_pipeline import VoiceCallHandler

CLINICAL_CONFIG = Path(__file__).resolve().parents[1] / "configs" / "clinical_triggers.yaml"
HANDOFF_CONFIG = Path(__file__).resolve().parents[1] / "configs" / "handoff_phrases.yaml"


class FailingClaudeProvider(BaseLLMProvider):
    """Simulates Claude returning HTTP 429 (Rate Limit / Quota Exceeded)."""
    provider_name = "claude_primary_simulated"

    def __init__(self, should_fail: bool = True):
        self.should_fail = should_fail
        self.call_count = 0

    def generate_stream(self, messages: list[dict], **kwargs) -> Iterator[Union[str, dict]]:
        self.call_count += 1
        if self.should_fail:
            raise LLMQuotaExceededError(
                "Anthropic API error: 429 rate_limit_error: Organization monthly budget exceeded",
                provider="claude",
                status_code=429,
            )
        yield "Claude response token. "
        yield {"text": "Claude response token.", "latency_ms": 150.0, "provider": "claude"}


class HealthyGeminiProvider(BaseLLMProvider):
    """Simulates Google Gemini serving the fallback turn."""
    provider_name = "gemini_fallback_simulated"

    def __init__(self, reply: str = "Hello from Gemini fallback! Your appointment is confirmed."):
        self.reply = reply
        self.call_count = 0

    def generate_stream(self, messages: list[dict], **kwargs) -> Iterator[Union[str, dict]]:
        self.call_count += 1
        for token in self.reply.split():
            yield token + " "
        yield {"text": self.reply, "latency_ms": 220.0, "provider": "gemini"}


class TestVoiceCanaryFailover(unittest.IsolatedAsyncioTestCase):

    async def test_claude_quota_exhaustion_failover_to_gemini_in_voice_call(self):
        """
        Controlled failure test:
        1. Caller speaks turn
        2. Claude raises 429 quota exhaustion
        3. FallbackLLMProvider catches error, triggers cooldown, initiates Gemini
        4. Gemini stream reaches VoiceCallHandler and transmits audio to Twilio
        5. Session history records complete turn without duplication
        6. Audit logger records RETRY_ATTEMPT failover event
        """
        outbound = []
        async def mock_send(msg): outbound.append(msg)

        audit = AuditLogger()
        metrics = MetricsRegistry()

        claude_provider = FailingClaudeProvider(should_fail=True)
        gemini_provider = HealthyGeminiProvider(reply="I have verified your account details.")

        fallback_llm = FallbackLLMProvider(
            primary=claude_provider,
            fallback=gemini_provider,
            cooldown_seconds=60.0,
            audit_logger=audit,
            metrics=metrics,
        )

        cm = ConversationManager(
            llm_service=fallback_llm,
            clinical_guard=HandoffDetector(config_path=CLINICAL_CONFIG),
            handoff_detector=HandoffDetector(config_path=HANDOFF_CONFIG),
            audit_logger=audit,
            metrics=metrics,
        )

        stt = MockSTTService()
        tts = MockTTSService(frame_count_per_word=1)
        session = CallSession(call_sid="CA_FAILOVER_1", stream_sid="MZ_FAILOVER_1", session_id="sess_fo_1")

        handler = VoiceCallHandler(
            session=session,
            send_to_twilio_fn=mock_send,
            conversation_manager=cm,
            stt_service=stt,
            tts_service=tts,
            audit_logger=audit,
            metrics=metrics,
        )

        await stt.connect()
        stt_task = asyncio.create_task(handler.process_stt_events())

        # Caller initiates turn
        await stt.push_event(STTEvent(STTEventType.FINAL_TRANSCRIPT, text="Please check my account status."))

        await asyncio.sleep(0.05)
        if handler._active_turn_task:
            await handler._active_turn_task

        # 1. Claude was called and failed
        self.assertEqual(claude_provider.call_count, 1)

        # 2. Gemini was called once as fallback
        self.assertEqual(gemini_provider.call_count, 1)

        # 3. Audio was produced and sent to Twilio
        media_events = [m for m in outbound if m.get("event") == "media"]
        self.assertGreater(len(media_events), 0, "Telephony audio frames must reach caller")

        # 4. Turn history contains exactly one assistant response (no duplication!)
        self.assertEqual(len(session.conversation_history), 2)
        self.assertEqual(session.conversation_history[0]["role"], "user")
        self.assertEqual(session.conversation_history[1]["role"], "assistant")
        self.assertIn("verified your account", session.conversation_history[1]["content"])

        # 5. Metric incremented for failover event
        self.assertEqual(metrics.get_counter("llm_failover_events_total"), 1)
        self.assertEqual(metrics.get_counter("llm_fallback_cooldown_triggered_total"), 1)

        # 6. Cooldown is active: subsequent turn routes directly to Gemini without calling Claude
        await stt.push_event(STTEvent(STTEventType.FINAL_TRANSCRIPT, text="Thank you, that was helpful."))
        await asyncio.sleep(0.05)
        if handler._active_turn_task:
            await handler._active_turn_task

        # Claude call count stayed at 1 (bypassed due to cooldown!)
        self.assertEqual(claude_provider.call_count, 1)
        # Gemini was called for the 2nd turn
        self.assertEqual(gemini_provider.call_count, 2)
        self.assertEqual(metrics.get_counter("llm_fallback_used_total"), 1)

        stt_task.cancel()
        await handler.handle_stop()


if __name__ == "__main__":
    unittest.main()