"""initial schema: sessions, memory_records, audit_events, security_events, idempotency_records

Revision ID: 0c8ab0c30f96
Revises: 
Create Date: 2026-08-19 11:29:00.026262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ab0c30f96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('policy', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_audit_events_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('ix_audit_events_request_id', 'audit_events', ['request_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('result_status', sa.String(length=32), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('memory_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint("category IN ('PREFERENCE', 'WORKFLOW_CONTEXT', 'COMMUNICATION_PREFERENCE')", name='ck_memory_records_category_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_records_user_id', 'memory_records', ['user_id'], unique=False)
    op.create_table('security_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','LOW','MEDIUM','HIGH','CRITICAL')", name='ck_security_events_severity_valid'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_security_events_type', 'security_events', ['type'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_intent', sa.String(length=128), nullable=True),
    sa.Column('workflow_state', sa.String(length=64), nullable=True),
    sa.Column('pending_action', sa.String(length=64), nullable=True),
    sa.Column('pending_parameters', sa.JSON(), nullable=False),
    sa.Column('confirmation_state', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'WAITING_FOR_INPUT', 'WAITING_FOR_CONFIRMATION', 'COMPLETED', 'EXPIRED', 'FAILED')", name='ck_sessions_status_valid'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_security_events_type', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_memory_records_user_id', table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_table('idempotency_records')
    op.drop_index('ix_audit_events_request_id', table_name='audit_events')
    op.drop_index('ix_audit_events_event_type', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
